feat: handle cancel messages
elastic-ipfs/bitswap-peer pull request #193
Opened 2023-02-23 14:58 UTC by vasco-santos

This PR adds handling of cancel messages from inflight operations. Using `p-queue` together with Abort Signal all the way would be my ideal solution, but that would require a huge refactor that would mean a long time to work on this.

Implementation details:
- added `inProcessingWantBlocks` and `inProcessingWantHaves` Maps to the handler context (each connection has its own context)
- decoupled previous `batchFetch` function into two function, with an initial step just for getting a normalized wantList with arrays for `wantedBlocks`, `wantedHave` and `canceled`
- `wantedBlocks` and `wantedHave` added to respective processing maps in the start of fetching, and canceled blocks flagged in respective processing maps (if still existing and not previously addressed)
- cleanup `inProcessing` maps in case of errors and messages not handled to avoid memory leaks

Closes https://github.com/web3-storage/w3infra/issues/149

2023-02-23 15:01 UTC, vasco-santos commented on test/handler.test.js
> +    t.equal(connectionSpy.send.callCount, 0) // Blocks requested and cancelled in same message
The mock actually intercepts the HTTP request from client, and given async operation means now we actually cancel everything 🎉

2023-02-23 15:01 UTC, vasco-santos commented on test/handler.test.js
> -    }))
third batch has wantBlock and wantBlock cancel

2023-02-27 15:57 UTC, alanshaw requested changes
I don't understand how this works. We create a new `context` for every bitswap message we recieve. So additional messages that are received on the same connection won't affect any in-flight responses...

2023-02-27 16:21 UTC, vasco-santos commented
> I don't understand how this works. We create a new context for every bitswap message we recieve. So additional messages that are received on the same connection won't affect any in-flight responses...

Yes 🤦🏼  I moved the Maps creation into `handler.js` to not initialise them in the tests too and did not notice it was being created in message scope. I would expect the context to be connection dependent but will keep as is and just moved tracking of in flight messages to be in connection scope, but out of message scope.

2023-02-28 16:03 UTC, alanshaw requested changes
🚀 this is awesome, there's just a few issues I think we need to iron out before merge.

2023-02-28 16:03 UTC, alanshaw commented on src/handler.js
> +            clearProcessingBlocks(normalizedWantlist, context)
I'm concerned we'll end up with a memory leak for canceled blocks that we already sent. Perhaps it should be an LRU also?

2023-02-28 18:14 UTC, vasco-santos commented
@alanshaw thanks for the review. Integrated your suggestions:
- single LRU per connection (value has the cancel type because there are no )
  - still not entirely sure. In practise, we should not receive at same time cancel for block and want and this should work fine. But if not the case, there will happen overwrites... To solve this, we need to go back to 2 data structures or play with key format. What do you think?
- added telemetry for count of success cancels and size. Followed pattern for metrics as commented `bitswap-request-size` here
- clear on disconnect/error

2023-03-01 15:12 UTC, alanshaw approved these changes
LGTM, please can we just use the existing LRU module though?

2023-03-01 15:28 UTC, vasco-santos commented on src/service.js
> +import LRU from 'quick-lru'
good catch

2023-03-01 15:54 UTC, vasco-santos commented
Deployed to dev https://github.com/elastic-ipfs/bitswap-peer/actions/runs/4305195468 and ran regression tests https://github.com/elastic-ipfs/bitswap-e2e-tests/actions/runs/4305374528 successfully 🎉

2023-03-01 15:54 UTC, merged